title: Ted's blog
description: > # this means to ignore newlines until "baseurl:"
  Contains some blog posts.

# social links
twitter_username: tedhudek
github_username:  tedhudek

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
